### PR TITLE
Migrate from Travis to Github Actions

### PR DESCRIPTION
**Pull request by bdeshi**
migrates repo CI method to github actions in tandem with OpenBangla/OpenBangla-Keyboard#127

excuse commit spam please. i've made numerous updates, fixes, refactors, etc to make buildman work better with latest master of main repo.

<sup>if this is merged, the README build status badge source should be updated afterwards.</sup>

### CODE REVIEW

**Comment by bdeshi** [comment]
package deployment can also be moved to gh-actions from transfer.sh:
[`bdeshi/openbangla-keyboard-buildman/tree/gh-actions-artifacts`](https://github.com/bdeshi/openbangla-keyboard-buildman/tree/gh-actions-artifacts)

A difference is that all generated packages get bundled into a single zip archive:
[`buildlog+artifact`](https://github.com/bdeshi/openbangla-keyboard-buildman/runs/416643143)

**Comment by mominul** [comment]
> package deployment can also be moved to gh-actions from transfer.sh:

Yeah, I had used transfer.sh as a hack. We should use a [github cli](https://github.com/j0057/github-release) for deploying the assets to OBK github releases page.

Could you also create a demo with jfrog cli for deploying the assets to bintray?

**Comment by bdeshi** [comment]
> Could you also create a demo with jfrog cli for deploying the assets to bintray?

that's the next step, it's what i'm working on now.

**Comment by bdeshi** [comment]
> Yeah, I had used transfer.sh as a hack. We should use a [github cli](https://github.com/j0057/github-release) for deploying the assets to OBK github releases page.

i think this entire process can be managed with a github workflow as well. For example, you could create a new release in the OpenBangla/OpenBangla-keyboard repo, and it will run buildman to generate packages and push them to necessary places.

**Comment by mominul** [comment]
> i think this entire process can be managed with a github workflow as well.

Please! :tada: :grin:

**Comment by bdeshi** [comment]
let's put that on the todo list, and let's see what happens to the bintray plan first.

**Comment by mominul** [comment]
Closing this PR, as you have said :grin:

**Comment by bdeshi** [comment]
oops, i meant to say merge this PR, sorry! :sweat_smile:

**Pull request closed without merging**
