### PR TITLE
Add .pkg extension to ArchLinux package.

### PR DESCRIPTION
**Pull request by mominul**
CC @bdeshi

### CODE REVIEW

**Comment by bdeshi** [comment]
it's perfectly okay. :slightly_smiling_face:

**Comment by mominul** [comment]
@bdeshi  Why there`.pkg` extension not present? https://travis-ci.org/OpenBangla/buildman/jobs/394658683#L1228 :confused:

**Comment by bdeshi** [comment]
that's what I thought. I'm on a free travis ci acct that runs for commits to the master branch only. so I marked my arch-build branch as master and pushed to that. waiting for results.

**Comment by mominul** [comment]
Ah! We are pulling from master branch https://github.com/OpenBangla/buildman/blob/6ed087e5fcac35f7ba7a8f72865997601fe69144/script.sh#L41 So the changes are not effecting. I will merge this and see the results then. But hoping for the best!

**Pull request merged**
